### ISSUE TITLE
Notifications page blank when no notifications

### ISSUE THREAD

**Issue by FerociousTruth** [LessWrong2/Lesswrong2#153] opened 2017-09-24 16:51 UTC
I have no notifications.  I click the notifications icon in the top right, click "All Notifications" and am taken to https://www.lesserwrong.com/inbox?select=Notifications this page is totally blank.

**Comment by Discordius** [comment] 2017-10-20 00:34
Yep, that's a bug. Shouldn't be too hard to fix.

**Comment by ForrestWeiswolf** [comment] 2018-05-14 23:58
I'm working on a fix for this. 

Having it say 'You have no notifications' is quite simple; making sure that it doens't say that when they just haven't loaded yet is a bit less straightforward, especially since I'm not familiar with Vulcan. 

Would you prefer that I make a pull request now, so that you can look it over, or should I finish reinstating the loading message first? (Or something else entirely... This isn't marked 'good first issue', so I hope it's okay if I jump in here.)

**Comment by Raemon** [comment] 2018-05-15 00:55
Hmm – there's a chance this was inadvertently fixed awhile ago (when I test
it out locally it seems to work as intended). On your current version of
the site does it appear to still have the bug by default?
ᐧ

**Comment by ForrestWeiswolf** [comment] 2018-05-15 14:39
Wait, notifications are in the sidebar now, aren't they? So https://www.lesserwrong.com/inbox?select=Notifications isn't even used anymore? If that's the case, then yes, it's been inadvertently fixed already.

**Comment by Raemon** [comment] 2018-05-15 15:12
Oh, I see.

https://www.lesserwrong.com/inbox?select=Notifications *is* still used
(sometimes) to see _all_ your notifications, but it's basically impossible
to get to that page until you have at least one notification (since the
link to it is in the sidebar)

So I don't think this technically needs to get done, but it might still be
worth doing as a simple "warm up" PR, unless you want to move on to
something else. (If you decide to continue this one, I'd lean even harder
in the "figure out how to properly wait for the loading to finish before
displaying the 'No notifications found' message", since most of the value
is in learning a bit about how vulcan works).

FYI, the relevant bits to learn are in the docs for the withList higher
order component (you can see at the bottom of the
NotificationsFullScreen.jsx component that it's getting wrapped in the
withList component during the registerComponent process. Wrapping something
in withList gives it some special prop, documented below:

http://docs.vulcanjs.org/resolvers.html#withList

And you can see some examples of how to apply that in the
posts/PostList.jsx item (which uses the withList props to determine whether
to show the PostList itself, or a loading screen, or a "no results"
message).
ᐧ

**Closed** 2018-09-01 02:35 UTC
Labels: 2. Medium Priority (Easy), 4. Bug
