### ISSUE TITLE
LaTeX Copy-Paste linking

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#944] opened 2018-09-05 17:57 UTC
Another, very serious issue with LaTeX support: When you copy/paste LaTeX objects, the resulting objects are permanently linked. Editing the content of one of them changes the content of another, which is not visible when editing but becomes visible once you save the post. This one made me doubt my sanity for a moment.

**Comment by Discordius** [comment] 2018-09-05 17:58
Lol, was just about to create the same issue

**Comment by jimrandomh** [comment] 2018-09-19 18:13
Duplicate of #703 .

**Closed by jimrandomh** 2018-09-19 18:13 UTC
Labels: 1. Important (Hard)
