### ISSUE TITLE
Multiline link to LW post displayed incorrectly in Firefox

### ISSUE THREAD

**Issue by mduczmal** [LessWrong2/Lesswrong2#3782] opened 2020-12-08 14:38 UTC
## Description
If there is a line break in a link to other LW post, the little circle after the link is misplaced in Firefox.

## Examples
_The Moral Void_
![czwarta_kropka](https://user-images.githubusercontent.com/20318304/101494056-262f9780-3967-11eb-8244-933d47bf49c8.png)
_Is Morality Preference?_
![kropka_yesterday](https://user-images.githubusercontent.com/20318304/101494068-2af44b80-3967-11eb-8a1e-ebe2703fc6fe.png)

Line break is a sufficient condition but not a necessary one for the issue to occur as the example below demonstrates.

_Topic That Must Not Be Named_
![dwie_kropki_na_raz](https://user-images.githubusercontent.com/20318304/101496954-af949900-396a-11eb-91fa-b1db4e224c82.png)
### Steps to reproduce

1. Select "New Post"
2. Enter title
3. Enter two line paragraph: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce porta pharetra mi, vitae tristique lectus congue eu."
4. Select entire paragraph
5. Select "Link"
6. Enter link to an existing post
7. Click "Submit"

#### Expected result
The link displays correctly in Chrome:
![expected_dot](https://user-images.githubusercontent.com/20318304/101494514-bcfc5400-3967-11eb-94ef-dd5774d6d779.png)

#### Actual result
However, in Firefox the circle is displayed over the first letter instead of the end of the paragraph
![actual_dot](https://user-images.githubusercontent.com/20318304/101492720-62fa8f00-3965-11eb-8678-fb33f20f8245.png)

## Browser and OS
Firefox 83.0, Ubuntu 20.04

**Comment by jimrandomh** [comment] 2021-05-17 17:59
Duplicate of https://github.com/LessWrong2/Lesswrong2/issues/3186 , should be fixed now.

**Closed by jimrandomh** 2021-05-17 17:59 UTC
