### ISSUE TITLE
Word count greatly overestimated for posts containing math

### ISSUE THREAD

**Issue by ksvanhorn** [LessWrong2/Lesswrong2#602] opened 2018-05-24 04:35 UTC
My post, "Sleeping Beauty Resolved?" is claimed to have 80,398 words. This is off by a **factor of 34**.

**Comment by jglamine** [comment] 2018-05-24 11:57
Thanks for reporting! This looks like a duplicate of issue #540

**Closed** 2018-09-01 02:47 UTC
