### ISSUE TITLE
Can't save PDF versions of pages on chrome

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#792] opened 2018-08-09 20:37 UTC
https://app.intercom.io/a/apps/wtb8z7sj/inbox/inbox/1487180/conversations/15409626665

From intercom:

 I seem to be having trouble saving pages as PDFs on Google Chrome. ("Ctrl + P, Save as PDF")

Might be a local problem, but I figured I'd give you a heads up

(For reference, by problems I mean "the thing loads, but it won't show me a preview, and clicking on 'Save as' makes it not respond")

**Comment by jimrandomh** [comment] 2018-08-10 00:09
I just did a quick assessment on the printability of our pages, and created separate issues for a few different things.

 * #793 Printed pages have cosmetic problems
 * #794 Can't print long posts if Sunshine Sidebar is visible

The issue this person is specifically complaining about is caused by #776, and seems to be fixed on the local branch I have where I've been working on that one. It seems that high CPU usage is worse in the context of rendering for print preview, for some reason; I don't know why exactly, and I don't have a way to get a debugger or profiler on the print-preview render, but being in a print preview seems to take the rendering time from 20s to "effectively never".

**Closed by jimrandomh** 2018-08-10 00:09 UTC
