### ISSUE TITLE
Special characters displayed bigger in editor

### ISSUE THREAD

**Issue by mduczmal** [LessWrong2/Lesswrong2#3816] opened 2020-12-18 10:33 UTC
## Description
Special characters appear to be bigger in the editor than the ASCII characters.

## Example
It is visible in the post editor:
![bigger_post](https://user-images.githubusercontent.com/20318304/102604163-13198600-4124-11eb-8c8b-792e0a1c4af7.png)
As well as in the question editor:
![bigger_question](https://user-images.githubusercontent.com/20318304/102604167-144ab300-4124-11eb-9d5c-30f139e5c56a.png)

## Steps to reproduce

1. Select "New Question" or "New Post".
2. Enter "ûçżéucze" in the body of the document.

## Browsers
Chrome 87.0 and Firefox 84.0

**Comment by Discordius** [comment] 2020-12-18 18:49
Yeah, this is a font issue, not clear what we can do about it. The problem is that our font doesn't cover those characters, so we fall back to a different font with a different x-height. 

Workaround would be to provide a better font as a fallback that has more similar sizing behavior.

**Comment by jimrandomh** [comment] 2021-09-18 22:14
I think this was fixed by Adobe adding more supported languages to the font. I can't currently reproduce it. If I compare the list of supported languages for Warnock Pro, our main font, on https://fonts.adobe.com/fonts/warnock#details-section+warnock-pro-light vs https://web.archive.org/web/20200805052611/https://fonts.adobe.com/fonts/warnock#details-section, I see that the list of supported languages has grown. I think we're serving the font in such a way that it got this update automatically, so this is fixed now.

**Closed by jimrandomh** 2021-09-18 22:14 UTC
