### ISSUE TITLE
Setting draft to null on a post makes it disappear

### ISSUE THREAD

**Issue by kronusaturn** [LessWrong2/Lesswrong2#3602] opened 2020-10-27 00:22 UTC
When creating a post or moving a post out of drafts, GreaterWrong sets the "draft" property to null. This worked until recently, but now it seems to make the post completely disappear from all listings -- it's no longer visible in the user's drafts, or anywhere else. However, it can still be linked to. I can make GW set the property to false instead, but affected posts should be brought back and the API should probably either handle null the same as false or throw an error in this case.

**Comment by Discordius** [comment] 2020-10-27 04:13
Looks like this breaks because some of our validation broke in this commit: https://github.com/LessWrong2/Lesswrong2/commit/3dcf2e7b37cec1537adf25bcb87c943f038da874

This PR fixes it: https://github.com/LessWrong2/Lesswrong2/pull/3603

Should be merged within the week.

**Comment by Discordius** [comment] 2020-10-27 04:27
(Note that this PR fixes this inconsistency by throwing an error, which is the intended behavior of the API)

**Comment by Discordius** [comment] 2020-10-27 04:31
I also migrated all historical posts, and manually processed them to decide which ones ended up being posted via some other way, or were spam. So there should be no remaining posts in the database with this inconsistency.

**Comment by Discordius** [comment] 2020-10-27 04:39
Relatedly: You also set the `url` field to I think the string "null" in a bunch of circumstances, as well as the `question` field to `null`. The second one will now also throw an error, the first one just results in a very weird looking linkpost. 

I can't currently find any instances of the `url` bug, but I've seen it while processing the posts with an invalid draft value (though it seems to have gone away after saving them again on LW, so I can't give you more detail atm).

**Comment by kronusaturn** [comment] 2020-10-27 05:27
Thanks, I noticed that too and both of those bugs should be fixed.

**Closed** 2020-10-27 21:20 UTC
