### ISSUE TITLE
The imported links from the original LW1.0 link posts appear to sometimes be broken

### ISSUE THREAD

**Issue by Discordius** [LessWrong2/Lesswrong2#22] opened 2017-06-17 01:49 UTC

**Comment by WalkerCodeRanger** [comment] 2017-09-24 15:00
I assume this issue is the same as what I am seeing.  For example, the link post from LW http://lesswrong.com/lw/o1r/how_feasible_is_the_rapid_development_of/ appears as https://www.lesserwrong.com/posts/Bqht6nhhPkJWcRAFd/how-feasible-is-the-rapid-development-of-artificial in LW 2.0 but that page doesn't actually have a link on it. Clicking the title does nothing and no other link can be found.

**Comment by jimrandomh** [comment] 2018-08-21 04:25
Duplicate of #489 .

**Closed by jimrandomh** 2018-08-21 04:25 UTC
Labels: 1. Important (Hard), 4. Bug
