### ISSUE TITLE
phantom major past revisions?

### ISSUE THREAD

**Issue by zackmdavis** [LessWrong2/Lesswrong2#2751] opened 2019-12-28 19:37 UTC
The site is claiming that [the post I just published](https://www.lesswrong.com/posts/y4bkJTtG3s5d6v36k/stupidity-and-dishonesty-explain-each-other-away) has "major past revisions." This is unwanted. (I did "Save as Draft" and edit once or twice before publishing (after drafting the post in my local text editor and pasting it into the website), but I don't think that should count as a "major revision", and it hasn't on previous posts.) When I click to view these alleged major past revisions, the pop-up list is empty.

![major_past_revisions](https://user-images.githubusercontent.com/1076988/71548674-6a987200-2966-11ea-9996-14472815c919.png)

**Comment by Discordius** [comment] 2019-12-28 20:15
Yep, looks like a bug. Looks like for some reason we skipped a version-number for this post and went right from 0.1.0 to 2.0.0. 

I have a model of what happened, and I think that might occur if a database request fails at the wrong time, or times out for some other reason, though it might also be something more mundane. 

The relevant lines of code are: 

```
const lastRevision = await Revisions.findOne({documentId: documentId, fieldName}, {sort: {editedAt: -1}}) || {}
  const { major, minor, patch } = extractVersionsFromSemver(lastRevision.version)
  switch (updateType) {
    case "patch":
      return `${major}.${minor}.${patch + 1}`
    case "minor":
      return `${major}.${minor + 1}.0`
    case "major":
      return `${major+1}.0.0`
```

And then in `extractVersionsFromSemver`: 

```
semver = semver || "1.0.0"
const [major, minor, patch] = semver.split(".").map((n) => parseInt(n, 10))
```

In particular this means if we fail to find a past revision, we assume that the previous revision was `1.0.0` which would exactly give rise to the observed behavior. 

I manually fixed the version-number on your post. I sadly can't reproduce it, so for now the best choice might be to wait until we observe this behavior again. 

Or, alternatively we could make the relevant code more robust, though no obvious changes come mind.

**Comment by zackmdavis** [comment] 2019-12-28 20:17
thanks :sparkling_heart:

**Comment by Discordius** [comment] 2019-12-28 21:53
Note: Bug also shows up on https://www.lesswrong.com/posts/JDdmcc4CmMDDo82rZ/an-emergency-fund-for-effective-altruists

I think this means it's probably reproducible, and I will try to look into it soon. Hopefully today.

**Comment by zackmdavis** [comment] 2020-01-01 19:06
Happened again with https://www.lesswrong.com/posts/jrLkMFd88b4FRMwC6/don-t-double-crux-with-suicide-rock (but, individual bug-instance reports like this are likely not useful, because I assume that once you have a fix, it shouldn't be hard to query for posts with a 2.0.0 but not a 1.0.0?).

**Comment by zackmdavis** [comment] 2020-01-04 22:34
Again: https://www.lesswrong.com/posts/trb9HPWFk8Gy9MBdN/less-wrong-poetry-corner-walter-raleigh-s-the-lie (If it isn't happening to everybody this consistently, maybe something my browser is doing makes it more likely? I'm on Firefox 71.0 on Xubuntu 16.04.)

**Comment by Discordius** [comment] 2020-01-04 22:42
I looked into it yesterday, and found the reason (I won't go into technical details). We have a fix that should ship next week. And it does indeed affect more users than just you.

**Comment by Discordius** [comment] 2020-01-04 22:43
For posterity, this was fixed in this PR:

**Closed** 2020-01-04 22:43 UTC
