### ISSUE TITLE
Occasional Network Errors

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#563] opened 2018-05-04 21:23 UTC
Since moving to lesswrong.com, occasionally get this error that appears on a PostList component, although it doesn't seem to actually cause any hard:

Network error: Network request failed with status 503 - ""

I remember something similar coming up when we did the _first_ partial move to lesswrong.com, and that I think we fixed it, but can't remember any of the details.

**Comment by jimrandomh** [comment] 2018-07-11 00:22
I'm seeing this too, and it does tend to break things when it happens.

**Comment by Discordius** [comment] 2018-07-11 19:10
Yep, this is pretty important to fix, but I don't really have any idea what causes it. Doing some better server-side profiling would help a lot here, but I don't know what a good way to get that set up is.

**Comment by jimrandomh** [comment] 2018-07-11 19:45
I think the first step is to habitually keep the network tab open when doing things on LW, catch it happening, and get a URL and a timestamp where it happened that can be matched up to server-side logs.

**Comment by Discordius** [comment] 2018-07-11 19:54
My model is that it's pretty random queries. We have lots of statistics in
our Apollo Engine about this happening, and I wasn't able to find patterns.

We can check it out together tomorrow or later today.

**Comment by jimrandomh** [comment] 2018-07-13 19:21
See #725 - at least some of this is caused by excessive server-side CPU usage when loading posts.

**Comment by jimrandomh** [comment] 2018-08-22 00:46
My current belief is that #725 is the cause of all of these, and that once everything in the pipeline is merged, node 8.12 is released, and we've upgrade to node 8.12, the problem will go away.

**Closed by jimrandomh** 2018-08-22 00:46 UTC
