### ISSUE TITLE
Show-Parent-Comment for nested comments

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#568] opened 2018-05-06 23:34 UTC
Right now, we have two types of comments:

"RecentComments" (RecentCommentsItem.jsx) – these appear in the Recent Discussion section. They show a comment in isolation. They have the ability to show a parent of the comment (by clicking on the up-arrow at the upper-left)

"Nested Comments" (CommentsItem.jsx) – these appear on the main post, and in the "show recent comments of this post" section of the PostItem component. These have the advantage of showing comments in a nested tree structure.

Nested comments are easier to follow, but they don't let you see their parent if you're looking at the a sub-section of a comment thread (such as when you expand a postItem to show the latest comments). 

Nested Comments should have an optional flag which enables a "show parent" button, which we only want to display if it's the top-most-nested-comment AND it actually has a parent. This will improve the PostItem latest comments section, and enable an updated Recent Discussion section that loads comments in a nested form.

**Comment by ForrestWeiswolf** [comment] 2018-07-06 15:46
I'm going to try implementing this. 

Having looked around the relevant components a bit, it seems like the nesting is handled by Comments_Node_, (which is rendering a CommentsItem), rather than by the CommentsItem component itself - is there a reason you're referring to CommentsItem as a nested comment here? 

It's not super important, but the unflatten function is imported as `import { unflatten } from '../../lib/modules/utils/unflatten';
' in PostsItemNewCommentsWrapper, but PostsCommentsThreadWrapper does `import { withList, Components, registerComponent, Utils} from 'meteor/vulcan:core'
` and calls Utils.unflatten. Is one of these preferred over the other? I've gone with the former for now, since it doesn't import other utils we're not using.


`    const nodeClass = classNames("comments-node", {
      "comments-node-root" : comment.level === 1,
      "comments-node-even" : comment.level % 2 === 0,
      "comments-node-odd"  : comment.level % 2 != 0,
      "comments-node-linked" : router.location.hash === "#" + comment._id && this.state.finishedScroll,
      "comments-node-deleted" : comment.deleted,
      "comments-node-its-getting-nested-here": comment.level > 8,
      "comments-node-so-take-off-all-your-margins": comment.level > 12,
      "comments-node-im-getting-so-nested": comment.level > 16,
      "comments-node-im-gonna-drop-my-margins": comment.level > 20,
      "comments-node-what-are-you-even-arguing-about": comment.level > 24,
      "comments-node-are-you-sure-this-is-a-good-idea": comment.level > 28,
      "comments-node-seriously-what-the-fuck": comment.level > 32,
      "comments-node-are-you-curi-and-lumifer-specifically": comment.level > 36,
      "comments-node-cuz-i-guess-that-makes-sense-but-like-really-tho": comment.level > 40,
    })
`
This is amazing

**Comment by Raemon** [comment] 2018-07-06 20:18
Thanks for doing this! Lack of this has been a pain for awhile but we kept having other stuff we needed to focus on.

I think I probably meant CommentsNode where I said CommentsItem. However, I think the place the new code should actually live is in CommentsItem. (CommentsItem is where all the UI actually lives)

Hypothetically, you could do a fairly complicated thing that loads additional comments into the same overall node structure. But, I think this would be a pain (I wasn't planning to do it when I first made this issue). Instead, the idea is for the top parent in the nested structure to just load additional parents the way RecentDiscussion does.

That may be a bit confusing - If it'd be helpful to do a quick skype or phonecall or something to talk through what we mean here, I'd  be happy to do that.

**Comment by ForrestWeiswolf** [comment] 2018-07-07 14:48
My current plan is:
Make the Recent Discussion render comments in a nested format, using CommentsNode (done)
Give the CommentsItem a prop that tells it whether to have a show parent button
Have Recent Discussion set that to true when it's the top-most-nested-comment and it has a parent 
Make the show parent button, work, either using code from RecentCommentsItem or loading additional comments into the same overall node structure. Loading them into the node structure would probably look better, but it would definitely be more involved.

Not sure if this all makes sens or not, though, so a phonecall seems like a good idea. You're probably busier than I am - when works for you?

**Comment by Raemon** [comment] 2018-07-07 19:16
I can do this afternoon (a couple hours from now) if that works.

**Comment by ForrestWeiswolf** [comment] 2018-10-06 15:17
This change has been merged (and reverted then added back in?), but the issue is still open. it's been awhile, but if there is unfinished business related to this that you'd like me to try to resolve, I'm interested in doing so.

>When you click the ‘show parent’ button, it shows the parent as a RecentCommentsItem. It would probably be desirable to replace that with a CommentsItem as well, which would be more consistent and allow RecentCommentsItem to be deleted entirely. However, getting a CommentsItem to display correctly under those circumstances involves some non-trivial manipulation of the styles on it, so I’m leaving that alone for now as well

This is what I remember being left undone last time we were working on this - might be worth taking a try at now?

**Comment by Raemon** [comment] 2018-10-06 19:15
I think there's a decent chance we're going to refactor the CommentsItem nontrivially, and the current implementation of this is good enough that I don't think it makes sense to move forward on it.

Closing the issue for now.

(I do think if you look over the "good first issue" tagged things there is some other stuff that might be worth working on if you're interested)

**Closed** 2018-10-06 19:18 UTC
Labels: 2. Medium Priority (Easy), 7. Feature, help wanted
