### ISSUE TITLE
 RSS feed missing an "author" tag for all posts.

### ISSUE THREAD

**Issue by Raemon** [LessWrong2/Lesswrong2#543] opened 2018-04-25 00:16 UTC
From intercom:

The RSS feed for lesswrong appears to be missing an "author" tag for all posts. As a result, the author in my RSS reader appears as "Lesswrong Development Server" (which is the channel title in the RSS feed and is presumably used as a fallback by my RSS reader). I think that the RSS feed should include an <author> tag for each post

**Comment by alexgloverl** [comment] 2018-05-04 23:37
Duplicate of: https://github.com/Discordius/Lesswrong2/issues/210

(Scanning through issues.)

**Comment by crybx** [comment] 2018-05-11 13:14
I made a fix (pull request) for this but if you think it needs to be done another way, let me know and I can try again.

**Comment by jimrandomh** [comment] 2018-07-10 02:50
The RSS spec defines "author" and "creator" as two separate fields; currently we only provide "creator", which may mean that some RSS readers are ignoring it. Simple solution is to put the user display name in both places.

**Comment by jimrandomh** [comment] 2018-07-10 22:10
See also discussion in #210 ; I believe this is working correctly (crybx's PR fixed it).

**Closed by jimrandomh** 2018-07-10 22:10 UTC
Labels: 3. Low Priority (Hard), help wanted
