### ISSUE TITLE
small bug in pop-up text that appears after subscribing to a user.

### ISSUE THREAD

**Issue by givoli** [LessWrong2/Lesswrong2#998] opened 2018-09-17 17:58 UTC
When you subscribe to a user, the little pop-up text that appears says:
**You have subscribed to "{name}" posts.**

(the actual string "{name}" appears instead of the users's name) 

Happened on Chrome 69.0.3497.92 (Windows 10).

**Comment by jimrandomh** [comment] 2018-09-18 00:38
The problem is in `SubscribeTo.jsx` (which was plucked from `vulcan-subscribe`), which generates strings by concatenating the entity-type and the action together, using that as a key into an internationalization dictionary. For unrelated reasons, this whole class is extremely problematic and needs a rewrite; the message formatting problem should go away when we do that.

**Comment by jimrandomh** [comment] 2018-09-18 22:41
Duplicate of #977 .

**Closed by jimrandomh** 2018-09-18 22:41 UTC
Labels: 4. Bug
