### ISSUE TITLE
Settings for postlists still don't show the current selections in black

### ISSUE THREAD

**Issue by ben-pace** [LessWrong2/Lesswrong2#2380] opened 2019-09-02 23:54 UTC
You can't tell that this is set to 'all posts' ordered by 'top':

<img width="811" alt="Screenshot 2019-09-02 at 16 53 43" src="https://user-images.githubusercontent.com/24915924/64135896-422aad80-cda2-11e9-90b0-47af1bc570f1.png">

**Comment by jimrandomh** [comment] 2019-09-03 22:54
Caused by a CSS specificity issue, fixed in https://github.com/LessWrong2/Lesswrong2/pull/2359 .

**Closed by jimrandomh** 2019-09-03 22:54 UTC
